from fpdf import FPDF
import datetime
import io

class ClinicalRecordPDF(FPDF):
    def header(self):
        # Hospital Header
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(20, 83, 136)  # Professional Blue
        self.cell(0, 10, 'VAIDIKA AI MEDICAL CENTER', ln=True, align='C')
        
        self.set_font('helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'Advanced AI-Powered Healthcare Solutions', ln=True, align='C')
        
        self.ln(5)
        self.set_draw_color(20, 83, 136)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by VaidikaAI on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')

def generate_clinical_pdf(patient_data, clinical_record):
    pdf = ClinicalRecordPDF()
    pdf.add_page()
    
    # 1. Patient Information Section
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, ' PATIENT INFORMATION', ln=True, fill=True)
    pdf.ln(2)
    
    pdf.set_font('helvetica', '', 11)
    col_width = 95
    
    # Row 1
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(30, 8, 'Name:')
    pdf.set_font('helvetica', '', 11)
    pdf.cell(col_width - 30, 8, f"{patient_data['name']}")
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(30, 8, 'Patient ID:')
    pdf.set_font('helvetica', '', 11)
    pdf.cell(col_width - 30, 8, f"{patient_data['patient_id']}", ln=True)
    
    # Row 2
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(30, 8, 'Age / Gender:')
    pdf.set_font('helvetica', '', 11)
    pdf.cell(col_width - 30, 8, f"{patient_data['age']} / {patient_data['gender']}")
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(30, 8, 'Language:')
    pdf.set_font('helvetica', '', 11)
    pdf.cell(col_width - 30, 8, f"{patient_data['language']}", ln=True)
    
    pdf.ln(10)
    
    # 2. Clinical Findings Section
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, ' CLINICAL FINDINGS', ln=True, fill=True)
    pdf.ln(5)
    
    # Diagnosis
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 8, 'Diagnosis:', ln=True)
    pdf.set_font('helvetica', '', 11)
    pdf.multi_cell(0, 8, f"{clinical_record['diagnosis']}")
    pdf.ln(5)
    
    # Symptoms
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 8, 'Reported Symptoms:', ln=True)
    pdf.set_font('helvetica', '', 11)
    symptoms_text = ", ".join(clinical_record['symptoms']) if clinical_record['symptoms'] else "None reported"
    pdf.multi_cell(0, 8, symptoms_text)
    pdf.ln(5)
    
    # 3. Prescriptions & Lab Tests
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(col_width, 8, 'Prescriptions:')
    pdf.cell(col_width, 8, 'Lab Tests Requested:', ln=True)
    
    pdf.set_font('helvetica', '', 11)
    y_before = pdf.get_y()
    
    # Prescriptions list
    rx_list = clinical_record['prescriptions'] if clinical_record['prescriptions'] else ["None"]
    for rx in rx_list:
        pdf.cell(col_width, 7, f"- {rx}", ln=True)
    
    y_after_rx = pdf.get_y()
    pdf.set_y(y_before)
    
    # Lab Tests list
    lab_list = clinical_record['lab_tests'] if clinical_record['lab_tests'] else ["None"]
    for lab in lab_list:
        pdf.set_x(10 + col_width)
        pdf.cell(col_width, 7, f"- {lab}", ln=True)
    
    y_after_lab = pdf.get_y()
    pdf.set_y(max(y_after_rx, y_after_lab) + 10)
    
    # 4. Severity & Follow-up
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(30, 8, 'Severity:')
    
    sev = clinical_record['severity'].lower()
    if sev == 'emergency':
        pdf.set_text_color(200, 0, 0) # Red
    elif sev == 'high':
        pdf.set_text_color(255, 140, 0) # Orange
    else:
        pdf.set_text_color(0, 128, 0) # Green
        
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(50, 8, f"{clinical_record['severity'].upper()}")
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(30, 8, 'Follow-up:')
    pdf.set_font('helvetica', '', 11)
    pdf.cell(0, 8, f"{clinical_record['followup']}", ln=True)
    
    pdf.ln(10)
    
    # 5. Clinical Notes
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 8, 'Clinical Notes:', ln=True)
    pdf.set_font('helvetica', 'I', 11)
    pdf.multi_cell(0, 8, f"{clinical_record['clinical_notes']}")
    
    # Final Disclaimer
    pdf.set_y(-30)
    pdf.set_font('helvetica', 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 4, "Disclaimer: This record is generated by AI based on the doctor-patient consultation. Please verify all clinical findings and prescriptions with a qualified medical professional.", align='C')

    return pdf.output()
